@startuml

skinparam SequenceLifeLineBackgroundColor LightYellow
title "Ufo dies"
actor Controller as control
participant "ufo: Ufo" as robot
participant ": AIController" as robotcontroller
participant "onAsteroid: Asteroid" as asteroid

control -> robot ++: Die()
robot -> robotcontroller ++: RemoveUfo(ufo)
robotcontroller --> robot --
robot -> asteroid ++: RemoveSpaceship(ufo)
asteroid --> robot --
robot --> control --

@enduml