@startuml

skinparam SequenceLifeLineBackgroundColor LightYellow
title "Ufo dies"
actor Controller as control
participant "ufo: Ufo" as robot
participant ": AIController" as robotcontroller
participant "a: Asteroid" as asteroid

control -> robot ++: Die()
robot -> robotcontroller ++: RemoveUfo(r)
robotcontroller --> robot --
robot -> asteroid ++: RemoveSpaceship(r)
asteroid --> robot --
robot --> control --

@enduml