@startuml
skinparam SequenceLifeLineBackgroundColor LightYellow

title "Asteroid explodes"

actor Controller as C

participant "a: Asteroid" as a
participant "c: AbstractSpaceship" as r
participant ": SunController" as sun
participant ": GameController" as game
participant "teleporter: TeleportGate" as tport

C -> a ++ : Explode()

loop for all AbstractSpaceship c in spaceships
    a -> r ++ : ReactToAsteroidExplosion()
    r --> a --
end

a -> sun ++ : RemoveAsteroid(a)
sun --> a --

a -> game ++ : RemoveAsteroid(a)
game --> a --

alt teleporter is not null

    a -> tport ++ : Explode()

    tport --> a --

end

a --> C --

@enduml