@startuml Uranium explodes
skinparam SequenceLifeLineBackgroundColor LightYellow

title Uranium reacts to sun nearby

actor "a: Asteroid" as a
participant "resource: Uranium" as res

a -> res ++: ReactToSunNearby(a)
res -> res ++: health--
deactivate res
alt health <= 0
    res -> a ++: Explode()
    a --> res --
end

res --> a --

@enduml