@startuml

skinparam SequenceLifeLineBackgroundColor LightYellow

title Uranium gets mined by Settler

actor Player as PLAYER

participant "s: Settler" as s
participant "onAsteroid: Asteroid" as a
participant "uranium: Uranium" as u
participant "storage: PlayerStorage" as st
participant "bill: BillOfMaterial" as bill


PLAYER -> s ++: Mine()

    s-->a ++: ReactToMineBy(s, s.storage)

        alt resource is NOT NULL && numOfLayersRemaining == 0

            a -> u ++: ReactToMine(onAsteroid, s, s.storage)

                u -> st ++: GetSumResource()
                st --> u --: sumResources

                alt sumResources < 10

                    u -> bill **: ctor()

                    u->bill++: AddMaterial(uranium)
                    bill --> u --

                    u->st ++: AddBill(bill)
                    st --> u --
                    
                    u -> a ++: SetResource(null)
                    a --> u -- 

                end

            u --> a--

        end

    a --> s --

s --> PLAYER --

@enduml