@startuml
skinparam SequenceLifeLineBackgroundColor LightYellow

title "AI takes a turn"

actor Controller as CTR
participant ": AIController" as aiController

CTR -> aiController ++ : Step()

loop for all Robot r in robots

    aiController -> aiController ++ : HandleRobot(r)
    deactivate aiController

end

loop for all TeleportGate t in teleporters

    aiController -> aiController ++ : HandleTeleportGate(t)
    deactivate aiController

end

loop for all Ufo u in ufos

    aiController -> aiController ++ : HandleUfo(u)
    deactivate aiController

end

aiController --> CTR --

@enduml