@startuml
skinparam SequenceLifeLineBackgroundColor LightYellow

title "Sunstorm starts"

actor Controller as C

participant ": SunController" as sun
participant "a: Asteroid" as a
participant "s: AbstractSpaceship" as c
participant "teleporter: TeleportGate" as t

C -> sun ++ : StartSunstorm()

    loop traverse 1/3 of asteroids with BFS (randomly)

        sun -> a ++ : ReactToSunstorm()

            alt numOfLayersRemaining > 0 OR resource isn't null

                a -> a ++ : KillAllSpaceships()

                    loop for all AbstractSpaceship s in spaceships

                        a -> c ++ : Die()
                        c --> a --

                    end

                deactivate a

            end

            alt teleporter isn't null

                a -> t ++ : ReactToSunstorm()

                    t -> t ++ : isCrazy = true
                    deactivate t

                t --> a --

            end

        a --> sun --

    end

sun --> C --

@enduml