@startuml

skinparam SequenceLifeLineBackgroundColor LightYellow

title Uranium gets mined by Ufo

actor Controller as PLAYER

participant "ufo: Ufo" as s
participant "onAsteroid: Asteroid" as a
participant "uranium: Uranium" as u


PLAYER -> s ++: Mine()

    s-->a ++: ReactToMineBy(ufo)

        alt resource is NOT NULL && numOfLayersRemaining == 0

            a -> u ++: ReactToMine(onAsteroid, ufo)

                u -> a ++: SetResource(null)
                a --> u --

            u --> a--

        end

    a --> s --

s --> PLAYER --

@enduml