@startuml

title "settler fills asteroid with uranium"

rectangle "s: Settler" as settler
rectangle "a: Asteroid" as onAsteroid
rectangle "u: Uranium" as uranium
rectangle "Skeleton" as skeleton
rectangle "ps: PlayerStorage" as storage

skeleton->settler : <<create>>
skeleton-->onAsteroid: <<create>>
skeleton-up->uranium: <<create>>
skeleton-up->storage: <<create>>

skeleton-down->onAsteroid: SetResource(NULL)
skeleton->onAsteroid: AddCrewmate(s)
skeleton->settler: SetStorage(ps)
skeleton-up->settler: SetOnAsteroid(a)
skeleton->storage: SetStoredMaterials(u)

@enduml