@startuml

title "settler fills asteroid with uranium"

rectangle "s: Settler" as settler
rectangle "onAsteroid: Asteroid" as onAsteroid
rectangle "uranium: Uranium" as uranium
rectangle "Skeleton" as skeleton

skeleton->settler : <<create>>
skeleton->onAsteroid: <<create>>
skeleton->uranium: <<create>>

skeleton-down->onAsteroid: SetResource(NULL)

@enduml