@startuml

skinparam SequenceLifeLineBackgroundColor LightYellow
title "Settler tries to/places a teleporter"
actor Player as player
participant "s: Settler" as settler
actor Tester as tester
participant "a: Asteroid" as asteroid
participant "t: TeleportGate" as teleport
participant "ps: PlayerStorage" as storage

player -> settler ++: PlaceTeleporter()
settler -> tester ++: Is there a teleporter here already?
tester --> settler --: yes/no
settler -> tester ++: Do I have at least one teleporter on me?
tester --> settler --: no/yes
settler -> storage ++: GetOneTeleporter()
storage --> settler -- : t

alt no teleporter on asteroid AND teleporter on settler
    settler -> teleport ++: SetHomeAsteroid(a)
    teleport --> settler --
    settler -> asteroid ++: SetTeleporter(t)
    asteroid --> settler --
    settler -> storage ++: RemoveTeleportGate(t)
    storage --> settler --

end
settler --> player --

@enduml
