@startuml usecase
left to right direction
:Player: -left-> (Settler builds Robot)
:Player: -left-> (Settler tries to build Robot)
:Player: -left-> (Settler builds TeleportGate)
:Player: -left-> (Settler tries to build TeleportGate)
:Player: -right-> (Settler mines Uranium)
:Player: -right-> (Settler mines Uranium with full storage)

:Player: -right-> (Settler tries to mine empty Asteroid)
:Player: -right-> (Settler tries to mine Asteroid that still has layers)
:Player: -right-> (Settler drills)
:Player: -up-> (Settler moves to Asteroid)

:Player: -up-> (Settler moves through teleport)
:Player: -up-> (Settler tries to use teleport gate without active pair)
:Player: -down-> (Settler places TeleportGate)
:Player: -down-> (Settler tries to place TeleportGate)
:Player: -down-> (Settler fills Asteroid with Uranium)

:Player: -down-> (Settler tries to fill Asteroid with Uranium)
newpage
left to right direction
:Controller: -left-> (Robot moves to Asteroid)
:Controller: -left-> (Robot drills)
:Controller: -right-> (Settler dies)

:Controller: -right-> (Robot dies)
:Controller: -right-> (Uranium explodes)
:Controller: -down-> (Asteroid explodes with a robot on it, moves to TeleportGate)
:Controller: -down-> (Asteroid explodes with a robot on it, moves to Asteroid)
:Controller: -down-> (Asteroid explodes with a settler on it)
:Controller: -down-> (Asteroid explodes with a TeleportGate on it, pair on Asteroid)
:Controller: -down-> (Asteroid explodes with a TeleportGate on it, pair in Storage)

:Controller: -right-> (Water evaporates)
:Controller: -up-> (Sun announces next Sunstorm)
:Controller: -up-> (Sun starts Sunstorm)
:Controller: -up-> (Sun pulls some Asteroids nearby)
@enduml