@startuml

skinparam SequenceLifeLineBackgroundColor LightYellow

title "settler mines uranium"

rectangle "ps: PlayerStorage" as storage
rectangle "s: Settler" as settler
rectangle "a: Asteroid" as onAsteroid

rectangle "Skeleton" as skeleton
rectangle "u: Uranium" as uranium

skeleton->settler : <<create>>
skeleton->onAsteroid: <<create>>
skeleton-up->uranium: <<create>>
skeleton->storage: <<create>>

skeleton-down->onAsteroid: SetResource(u)
skeleton->onAsteroid: AddCrewmate(s)
skeleton-down->onAsteroid: SetOnAsteroid(a)
skeleton-up->settler: SetStorage(ps)


@enduml