@startuml

skinparam SequenceLifeLineBackgroundColor LightYellow

actor Controller as controller

controller -> Mr_Krabs ++ : DoDose(c: Ketamine)
loop until overdosed
    Mr_Krabs -> Mr_Krabs : DoKetamine()
    activate Mr_Krabs
    deactivate Mr_Krabs
end
Mr_Krabs -> Mr_Krabs: Fuckin dies()
activate Mr_Krabs
deactivate Mr_Krabs
Mr_Krabs --> controller
@enduml