@startuml Settler moves through teleport

title Settler moves through teleport

skinparam SequenceLifeLineBackgroundColor LightYellow

actor Player as player

participant "s: Settler" as s
participant "gate: TeleportGate" as gate
participant "pair: TeleportGate" as pair

participant "targetAsteroid: Asteroid" as a2

participant "onAsteroid: Asteroid" as a1




player -> s ++ : Move(gate)

s -> gate ++ : ReactToMove(onAsteroid,s)

gate -> pair ++ : GetHomeAsteroid()
pair --> gate --: targetAsteroid

note right : pair has home_asteroid

alt targetAsteroid != null
    gate -> a2 ++ : ReactToMove(onAsteroid,s)
    a2 --> gate --
end

gate --> s --

s --> player --

@enduml