@startuml Water evaporates

skinparam SequenceLifeLineBackgroundColor LightYellow

actor Controller as controller
participant "a:Asteroid" as a
participant "resource: Water" as res


controller -> a ++ :ReactToSunNearby()
alt sun is nearby
    a -> res ++: ReactToSunNearby(a)
    res -> a ++: SetResource(null)
    a --> res --
    res --> a --
end
a --> controller

@enduml