@startuml seq

skinparam SequenceLifeLineBackgroundColor LightYellow

title "EnvironmentPanel gets updated"

participant "gameFrame: GameFrame" as gameFrame
participant "env: EnvironmentPanel" as env
participant ": TurnController" as turnC

gameFrame -> env ++: UpdateComponent()
env -> turnC ++: GetPlayer()
turnC -> env --: player

participant "player: Settler" as settler

env -> settler ++: GetOnAsteroid()
settler -> env --: onAsteroid

participant "onAsteroid: Asteroid" as asteroid

env -> asteroid ++: GetNeighbours()
asteroid -> env --: neighbours

env -> gameFrame --

@enduml