@startuml

title "settler tries to fill asteroid with uranium"

rectangle "s: Settler" as settler
rectangle "onAsteroid: Asteroid" as onAsteroid

settler-down->onAsteroid : SetResource(s, uranium)

@enduml