@startuml

skinparam SequenceLifeLineBackgroundColor LightYellow

title "settler tries to mine asteroid that still has layers"

rectangle "s: Settler" as settler
rectangle "onAsteroid: Asteroid" as onAsteroid

settler->onAsteroid : ReactToMineBy(s)

@enduml