@startuml
skinparam SequenceLifeLineBackgroundColor LightYellow

title "Asteroid explodes with a robot on it (moves to TeleportGate)"

actor Controller as C

participant "a: Asteroid" as a
participant "neighbour: TeleportGate" as neighbour
participant "r: Robot" as r
participant ": SunController" as sun
participant ": GameController" as game

C -> a ++ : Explode()

a -> r ++ : ReactToAsteroidExplosion() 
    r -> a ++ : GetRandomNeighbour()
    return neighbour
    r -> r ++ : Move(neighbour)
    deactivate r
r --> a --

a -> sun ++ : RemoveAsteroid(a)
sun --> a --

a -> game ++ : RemoveAsteroid(a)
game --> a --

alt teleporter is null
end

a --> C --

@enduml