@startuml

skinparam SequenceLifeLineBackgroundColor LightYellow

title "settler mines uranium with full inventory"

rectangle "s: Settler" as settler
rectangle "onAsteroid: Asteroid" as onAsteroid
rectangle "uranium: Uranium" as uranium
rectangle "storage: PlayerStorage" as storage

settler->onAsteroid : ReactToMineBy(s)
onAsteroid -> uranium : ReactToMine(onAsteroid, s)
uranium -> storage : GetSumResource()
storage -> uranium : sumStorage


@enduml